version: "3.7"
services:
  mysql-database:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
  test:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mysql-database